### ISSUE TITLE
task and command as string

### ISSUE THREAD

**Issue by trntv** [trntv/wilson#15]
Stage in pipeline definition:
```
pipeline:
  tasks:
    - task1
    - task: task2
```

Command in task definition
```
tasks:
  task1:
    command: env
```
